### ISSUE TITLE
CORS Policy

### ISSUE THREAD

**Issue by ivanzy** [xAlessandroC/harvester-adapter#4]
I'm not able to access the API from the browser due to CORS policy. 

> Access to XMLHttpRequest at 'http://137.204.57.93:7739/harvester/simulation' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by xAlessandroC** [comment]
The problem is now solved with the #5 pull request.
